openapi: 3.0.0

info:
  title: API
  description: API
  version: 1.0.0

tags:
  - name: api
    description: API endpoint

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  "/api/healthcheck":
    get:
      tags:
        - api
      responses:
        200:
          $ref: "#/components/responses/HealthcheckResponse"

components:
  headers:
    XRequestID:
      description: Request correlation identifier
      schema:
        type: string
      required: true

  parameters:
    XRequestID:
      name: X-Request-ID
      in: header
      description: Request correlation identifier
      schema:
        type: string
      required: true

  schemas:
    HealthcheckResponseBody:
      type: object
      properties:
        buildDate:
          type: string
        buildSha:
          type: string
        buildNumber:
          type: string
      required:
        - buildDate
        - buildSha
        - buildNumber
      additionalProperties: false

  responses:
    HealthcheckResponse:
      description: Successful healthcheck response
      headers:
        X-Request-ID:
          $ref: "#/components/headers/XRequestID"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HealthcheckResponseBody"
