name: Quality Checks
run-name: ${{ github.actor }} is checking project quality.
on: [push]
jobs:
    QualityChecks:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Install Node via nvm
              shell: bash -l {0}
              run: nvm install
            - name: Install Dependencies
              run: npm ci
            - name: Run quality checks
              run: npm run qualityChecks
            - name: Upload code coverage report
              uses: actions/upload-artifact@v4
              with:
                  name: code-coverage-report
                  path: coverage
